import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, useLocation, useNavigate } from 'react-router-dom';
import {
  Activity, ArrowLeft, Bell, CalendarDays, Check, ChevronRight, ClipboardList,
  Download, Eye, FileText, Filter, LogIn, LogOut, Menu, Pencil, Plus,
  Search, Settings, ShieldCheck, Trash2, Upload, UserPlus, UserRound, Users, X
} from 'lucide-react';
import './styles.css';

const KEY = 'lanbeth-care-state-v3';
const AUTH_KEY = 'lanbeth-care-auth-v3';
const AUTH_USER_KEY = 'lanbeth-care-user-v3';
const THEME_KEY = 'lanbeth-care-theme-v3';

const seed = {
  clients: [
    { id:'CL-012-2024-001', initials:'JD', name:'John Doe', email:'john.doe@gmail.com', phone:'+1 (555) 123-4567', clinician:'Dr. Sarah Johnson', status:'Active', dob:'15 March 1952', address:'24 Resolution Road, London' },
    { id:'CL-024-2024-002', initials:'ES', name:'Emily Smith', email:'emily.smith@gmail.com', phone:'+1 (555) 234-5678', clinician:'Dr. Michael Chen', status:'Active', dob:'21 July 1958', address:'12 Green Lane, London' },
    { id:'CL-031-2024-003', initials:'MB', name:'Michael Brown', email:'michael.brown@gmail.com', phone:'+1 (555) 345-6789', clinician:'Nurse Emma Wilson', status:'Inactive', dob:'03 February 1949', address:'8 Care Street, London' },
    { id:'CL-044-2024-004', initials:'SJ', name:'Sarah Johnson', email:'sarah.johnson@gmail.com', phone:'+1 (555) 456-7890', clinician:'Dr. James Anderson', status:'Active', dob:'10 October 1960', address:'40 Homecare Avenue, London' },
    { id:'CL-052-2024-005', initials:'DW', name:'David Wilson', email:'david.wilson@gmail.com', phone:'+1 (555) 567-8901', clinician:'Dr. Lisa Taylor', status:'Active', dob:'17 May 1955', address:'7 Resolution Road, London' },
    { id:'CL-067-2024-006', initials:'LM', name:'Lisa Martinez', email:'lisa.martinez@gmail.com', phone:'+1 (555) 678-9012', clinician:'Dr. Michael Chen', status:'Active', dob:'29 November 1963', address:'91 Green Road, London' }
  ],
  staff: [
    { id:'ST-001', initials:'JS', name:'John Smith', role:'Care Worker', email:'john.smith@gmail.com', status:'Active', phone:'+1 (555) 345-6789', employment:'Full Time', startDate:'12 January 2024' },
    { id:'ST-002', initials:'EW', name:'Emma Wilson', role:'Senior Carer', email:'emma.wilson@gmail.com', status:'Active', phone:'+1 (555) 222-1020', employment:'Full Time', startDate:'08 March 2025' },
    { id:'ST-003', initials:'MC', name:'Michael Chen', role:'Nurse', email:'michael.chen@gmail.com', status:'Active', phone:'+1 (555) 220-1190', employment:'Part Time', startDate:'11 April 2025' },
    { id:'ST-004', initials:'SW', name:'Sarah Williams', role:'Care Worker', email:'sarah.williams@gmail.com', status:'Active', phone:'+1 (555) 120-9000', employment:'Full Time', startDate:'14 June 2026' }
  ],
  reports: [
    { id:'RP-001', date:'18 Aug 2026', by:'John Smith', type:'Daily Care Report', status:'Submitted' },
    { id:'RP-002', date:'15 Aug 2026', by:'Emma Wilson', type:'Care Review', status:'Submitted' },
    { id:'RP-003', date:'10 Aug 2026', by:'Sarah Williams', type:'Weekly Report', status:'Submitted' }
  ],
  documents: [
    { id:'DOC-001', name:'Care Plan.pdf', type:'Care Plan', uploaded:'12 Aug 2026', expiry:'12 Nov 2026', status:'Valid' },
    { id:'DOC-002', name:'Medication List.pdf', type:'Medical', uploaded:'10 Aug 2026', expiry:'10 Nov 2026', status:'Valid' },
    { id:'DOC-003', name:'Identity Document.pdf', type:'Identity', uploaded:'04 Jan 2025', expiry:'04 Jan 2026', status:'Expired' }
  ],
  audit: [
    ['18 Aug 2026 09:40','Admin','Viewed client','Clients','192.168.1.10'],
    ['18 Aug 2026 09:12','Admin','Uploaded document','Documents','192.168.1.10'],
    ['17 Aug 2026 16:30','Admin','Edited staff','Staff','192.168.1.10'],
    ['17 Aug 2026 14:22','Admin','Generated report','Reports','192.168.1.10']
  ]
};

const demoAccount = { email:'admin@lanbethcare.com', password:'Admin@123', name:'Portal Admin' };

function loadState(){ try { return JSON.parse(localStorage.getItem(KEY)) || seed; } catch { return seed; } }
function saveState(state){ localStorage.setItem(KEY, JSON.stringify(state)); }
function loadAccounts(){ try { return JSON.parse(localStorage.getItem('lanbeth-accounts-v3')) || [demoAccount]; } catch { return [demoAccount]; } }
function saveAccounts(a){ localStorage.setItem('lanbeth-accounts-v3', JSON.stringify(a)); }

function App(){
  const [data,setData] = useState(loadState);
  const [auth,setAuth] = useState(()=>localStorage.getItem(AUTH_KEY)==='1');
  const [authUser,setAuthUser] = useState(()=>{try{return JSON.parse(localStorage.getItem(AUTH_USER_KEY))||demoAccount}catch{return demoAccount}});
  const [theme,setTheme] = useState(()=>localStorage.getItem(THEME_KEY)||'light');
  useEffect(()=>saveState(data),[data]);
  useEffect(()=>{localStorage.setItem(THEME_KEY,theme)},[theme]);
  return <BrowserRouter><Shell data={data} setData={setData} auth={auth} setAuth={setAuth} authUser={authUser} setAuthUser={setAuthUser} theme={theme} setTheme={setTheme}/></BrowserRouter>;
}

function Shell({data,setData,auth,setAuth,authUser,setAuthUser,theme,setTheme}){
  const loc=useLocation(), nav=useNavigate();
  const [collapsed,setCollapsed]=useState(false);
  const [mobileOpen,setMobileOpen]=useState(false);
  if(!auth){
    if(loc.pathname==='/login') return <AuthPage mode="login" onAuth={(account)=>{setAuth(true);setAuthUser(account);localStorage.setItem(AUTH_KEY,'1');localStorage.setItem(AUTH_USER_KEY,JSON.stringify(account));nav('/dashboard')}}/>;
    if(loc.pathname==='/signup') return <AuthPage mode="signup" onAuth={(account)=>{setAuth(true);setAuthUser(account);localStorage.setItem(AUTH_KEY,'1');localStorage.setItem(AUTH_USER_KEY,JSON.stringify(account));nav('/dashboard')}}/>;
    return <Landing onLogin={()=>nav('/login')} onSignup={()=>nav('/signup')}/>;
  }
  const logout=()=>{setAuth(false);setAuthUser(null);localStorage.removeItem(AUTH_KEY);localStorage.removeItem(AUTH_USER_KEY);nav('/')};
  return <div className={'app '+(collapsed?'collapsed ':'')+(mobileOpen?'mobile-open ':'')+`theme-${theme}`}>
    {mobileOpen&&<button className="sidebar-overlay" aria-label="Close menu" onClick={()=>setMobileOpen(false)}/>}
    <Sidebar collapsed={collapsed} mobileOpen={mobileOpen} toggle={()=>setCollapsed(v=>!v)} closeMobile={()=>setMobileOpen(false)} nav={nav} logout={logout}/>
    <main className="main"><Topbar nav={nav} logout={logout} email={authUser?.email||'admin@lanbethcare.com'} theme={theme} toggleTheme={()=>setTheme(t=>t==='light'?'dark':'light')} openMenu={()=>setMobileOpen(true)} toggleSidebar={()=>setCollapsed(v=>!v)}/><div className="content"><PageRouter nav={nav} data={data} setData={setData}/></div></main>
  </div>;
}

function Brand(){return <div className="brand"><span className="brand-mark">L</span><div><b>Lambeth<span>Care</span></b><small>Resolution Homecare</small></div></div>}

function Landing({onLogin,onSignup}){const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}); return <div className="landing">
  <video className="landing-video" autoPlay muted loop playsInline poster="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=2200&q=85"><source src="https://cdn.coverr.co/videos/coverr-a-doctor-talking-to-a-patient-1572/1080p.mp4" type="video/mp4"/></video>
  <div className="landing-image"/>
  <div className="landing-overlay"/>
  <header className="landing-nav"><button className="brand brand-button" onClick={()=>scroll('home')}><Brand/></button><nav className="landing-links"><button onClick={()=>scroll('home')}>HOME</button><button onClick={()=>scroll('services')}>OUR SERVICE</button><button onClick={()=>scroll('contact')}>CONTACT US</button></nav><div className="landing-auth"><button className="ghost-light" onClick={onLogin}>Sign In</button><button className="primary" onClick={onSignup}><UserPlus size={16}/> Create Account</button></div></header>
  <section id="home" className="hero"><div className="hero-copy"><span className="eyebrow">SMARTER HOMECARE MANAGEMENT</span><h1>Care management built around <span>people.</span></h1><p>Coordinate clients, staff, documents, reports and care activity from one secure, beautifully organised portal.</p><div className="hero-actions"><button className="primary big" onClick={onLogin}><LogIn size={18}/> Sign In</button><button className="ghost-light big" onClick={onSignup}>Create an account <ChevronRight size={18}/></button></div><div className="trust"><span><Check/> Secure workflow</span><span><Check/> Responsive portal</span><span><Check/> Centralised records</span></div></div></section>
  <section id="services" className="landing-section"><div className="landing-section-inner"><span className="eyebrow">OUR SERVICE</span><h2>Everything your care team needs.</h2><p>One connected workspace for managing people, compliance and daily care operations.</p><div className="service-grid">{[['Client Care','Profiles, care activities, medication and documents in one place.'],['Staff Management','Manage staff profiles, documents, induction and compliance.'],['Reports & Compliance','Keep reports, policies, audit history and expiry alerts organised.']].map(([title,text],i)=><article key={title} className="service-card"><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><button onClick={onLogin}>Explore portal <ChevronRight size={15}/></button></article>)}</div></div></section>
  <section id="contact" className="landing-contact"><div><span className="eyebrow">CONTACT US</span><h2>Ready to manage care with confidence?</h2><p>Sign in to your existing account or create a new portal account to get started.</p></div><div className="contact-actions"><button className="primary big" onClick={onLogin}>Sign In</button><button className="outline big" onClick={onSignup}>Create Account</button></div></section>
  <footer className="landing-footer"><Brand/><div><span>© 2026 LanbethCare. All rights reserved.</span><button onClick={()=>scroll('home')}>Back to top ↑</button></div></footer>
</div>}

function AuthPage({mode,onAuth}){
  const signup=mode==='signup'; const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState('');
  const submit=e=>{e.preventDefault(); setError(''); const accounts=loadAccounts(); const clean=email.trim().toLowerCase(); if(!/^\S+@\S+\.\S+$/.test(clean)){setError('Enter a valid email address.');return} if(password.length<6){setError('Password must be at least 6 characters.');return} if(signup){if(accounts.some(a=>a.email===clean)){setError('An account with this email already exists. Please sign in.');return} const account={email:clean,password,name:name.trim()||'Portal User'}; saveAccounts([...accounts,account]); onAuth(account)} else {const account=accounts.find(a=>a.email===clean && a.password===password); if(!account){setError('Email or password is incorrect. Use a registered account.');return} onAuth(account)}};
  return <div className="auth-screen"><div className="auth-visual"><div className="auth-visual-bg"/><div className="auth-copy"><Brand/><span className="eyebrow">LANBETHCARE PORTAL</span><h1>{signup?'Start your care portal journey.':'Welcome back to better care management.'}</h1><p>Securely manage care operations with a clear, connected workflow.</p></div></div><div className="auth-panel"><button className="back-home" onClick={()=>location.href='/'}>← Back to home</button><div className="auth-form"><Brand/><span className="eyebrow">{signup?'NEW ACCOUNT':'ADMIN ACCESS'}</span><h1>{signup?'Create your account':'Sign in to your account'}</h1><p>{signup?'Use your email to create a new portal account.':'Enter the email and password for your existing account.'}</p><form onSubmit={submit}>{signup&&<label>Full Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your full name"/></label>}<label>Email Address<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" required/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Enter password" required/></label>{error&&<div className="form-error">{error}</div>}<button className="primary big full" type="submit">{signup?'Create Account':'Sign In'} <ChevronRight size={17}/></button></form><div className="auth-switch">{signup?'Already have an account?':'Don’t have an account?'} <button onClick={()=>location.href=signup?'/login':'/signup'}>{signup?'Sign in':'Create one'}</button></div>{!signup&&<div className="demo-note"><b>Demo account</b><span>admin@lanbethcare.com</span><span>Admin@123</span></div>}</div></div></div>
}

function Sidebar({collapsed,toggle,mobileOpen,closeMobile,nav,logout}){const loc=useLocation(); const items=[['/dashboard','Dashboard',ClipboardList],['/staff','Staff Manage',UserRound],['/clients','Manage Clients',Users],['/expiry-documents','Expiry document alert',CalendarDays],['/generate-report','Generate Report',FileText],['/policies','Policy',ShieldCheck],['/audit-log','Staff Audit Logs',Activity],['/induction','Staff Induction',Check]];return <aside className={'sidebar '+(mobileOpen?'open':'')}><div className="side-top"><Brand/><button className="icon-btn" onClick={toggle}><Menu/></button></div><div className="side-profile"><span className="side-profile-icon"><ShieldCheck size={15}/></span><div><b>Admin Portal</b><small>Secure workspace</small></div></div><div className="side-scroll">{items.map(([p,t,I])=><button key={p} title={collapsed?t:''} className={'side-item '+(loc.pathname===p?'active':'')} onClick={()=>{nav(p);closeMobile()}}><I/><span>{t}</span></button>)}</div><div className="side-bottom"><button className="side-item" onClick={()=>{nav('/settings');closeMobile()}}><Settings/><span>Settings</span></button><button className="logout" onClick={logout}><LogOut/><span>Log Out</span></button></div></aside>}
function Topbar({nav,logout,email,theme,toggleTheme,openMenu,toggleSidebar}){return <header className="topbar"><div className="top-left"><div className="crumb"><span>LanbethCare</span><ChevronRight size={15}/><b>Admin Portal</b></div></div><div className="top-actions"><button className="icon-btn theme-toggle" title={theme==='light'?'Switch to dark mode':'Switch to light mode'} onClick={toggleTheme}>{theme==='light'?<span>☾</span>:<span>☀</span>}</button></div></header>}

function PageRouter({nav,data,setData}){const p=useLocation().pathname; const props={nav,data,setData}; const map={
 '/dashboard':<Dashboard {...props}/>, '/clients':<Clients {...props}/>, '/client-profile':<ClientProfile {...props}/>, '/medication':<ClientSub title="Medication" {...props} type="medication"/>, '/favorite-activities':<ClientSub title="Favorite Activities" {...props} type="activities"/>, '/daily-care':<ClientSub title="Daily Care" {...props} type="care"/>, '/client-documents':<Documents {...props}/>, '/reports':<Reports {...props}/>, '/edit-client':<EditClient {...props}/>, '/expiry-documents':<Expiry {...props}/>, '/staff':<Staff {...props}/>, '/staff-profile':<StaffProfile {...props}/>, '/staff-documents':<StaffDocuments {...props}/>, '/staff-expiry':<StaffExpiry {...props}/>, '/upload-staff-document':<UploadStaff {...props}/>, '/add-staff':<EditStaff {...props} add/>, '/edit-staff':<EditStaff {...props}/>, '/policies':<Policies {...props}/>, '/upload-policy':<UploadPolicy {...props}/>, '/generate-report':<GenerateReport {...props}/>, '/audit-log':<AuditLog {...props}/>, '/induction':<Induction {...props}/>, '/induction-profile':<InductionProfile {...props}/>, '/edit-induction':<EditInduction {...props}/>, '/add-induction':<EditInduction {...props} add/>, '/report-history':<ReportHistory {...props}/>, '/settings':<Simple title="Settings" {...props}/>
}; return map[p]||<Dashboard {...props}/>}

function Header({title,sub,nav,back}){return <div className="page-head">{back&&<button className="icon-btn" onClick={back}><ArrowLeft/></button>}<div><div className="eyebrow">LANBETHCARE</div><h1>{title}</h1>{sub&&<p>{sub}</p>}</div><div className="head-actions"><button className="icon-btn" title="Notifications" onClick={()=>window.alert('You have no new notifications.')}><Bell size={16}/></button></div></div>}
function Dashboard({nav,data}){const active=data.clients.filter(c=>c.status==='Active').length; return <><Header title="LANBETH RESOLUTION HOMECARE" sub="Manage clients, staff, reports, and more."/><div className="stats"><Stat icon={<Users/>} label="Total Clients" value={data.clients.length} trend="+8.2% this month"/><Stat icon={<UserRound/>} label="Active Staff" value={data.staff.filter(s=>s.status==='Active').length} trend="+2 new this month"/><Stat icon={<FileText/>} label="Reports Submitted" value={data.reports.length} trend="12 this week"/><Stat icon={<CalendarDays/>} label="Expiring Documents" value="03" trend="Needs attention" danger/></div><div className="dashboard-grid"><section className="section-card welcome-card"><div><span className="eyebrow">ADMIN DASHBOARD</span><h2>Everything important, in one place.</h2><p>Jump into your client and staff records or review documents requiring attention.</p><div className="quick-actions"><button onClick={()=>nav('/clients')}><Users/> Manage Clients</button><button onClick={()=>nav('/staff')}><UserRound/> Manage Staff</button><button onClick={()=>nav('/reports')}><FileText/> View Reports</button></div></div><div className="dashboard-illustration"><Activity size={110}/></div></section><section className="section-card"><div className="section-title"><div><span className="eyebrow">OVERVIEW</span><h2>Care activity</h2></div><button className="outline small" onClick={()=>nav('/audit-log')}>View audit log</button></div><div className="activity-list"><ActivityRow title="Client profile viewed" meta="John Doe · 12 minutes ago"/><ActivityRow title="Document uploaded" meta="John Smith · 34 minutes ago"/><ActivityRow title="Weekly report submitted" meta="Sarah Williams · 1 hour ago"/></div></section></div><div className="watermark">LAMBETH RESOLUTIONS</div></>}
function Stat({icon,label,value,trend,danger}){return <div className="stat-card"><span className={'stat-icon '+(danger?'danger':'')}>{icon}</span><div><small>{label}</small><strong>{value}</strong><em className={danger?'danger-text':''}>{trend}</em></div></div>}
function ActivityRow({title,meta}){return <div className="activity-row"><span><Check size={15}/></span><div><b>{title}</b><small>{meta}</small></div><ChevronRight size={16}/></div>}

function Clients({nav,data,setData}){const [search,setSearch]=useState(''); const [modal,setModal]=useState(null); const filtered=data.clients.filter(c=>(c.name+c.email).toLowerCase().includes(search.toLowerCase())); const remove=id=>{setData({...data,clients:data.clients.filter(c=>c.id!==id)});setModal(null)}; return <><Header title="Manage Clients" sub="View and manage all client information."/><div className="toolbar"><div className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or email..."/></div><select><option>All Status</option><option>Active</option><option>Inactive</option></select><button className="outline" onClick={()=>window.alert('Use the search and status controls to filter records.')}><Filter size={14}/> More Filters</button><button className="primary" onClick={()=>nav('/edit-client')}><Plus size={15}/> Add New Client</button></div><div className="client-grid">{filtered.map(c=><ClientCard key={c.id} data={c} onView={()=>setModal({type:'view',item:c})} onEdit={()=>setModal({type:'edit',item:c})} onDelete={()=>setModal({type:'delete',item:c})}/>)}</div>{modal&&<Modal title={modal.type==='delete'?'Delete Client':modal.type==='edit'?'Edit Client':'Client Details'} onClose={()=>setModal(null)}>{modal.type==='view'?<ClientDetail c={modal.item}/>:modal.type==='edit'?<InlineEdit item={modal.item} fields={['name','email','phone','clinician','status']} onSave={v=>{setData({...data,clients:data.clients.map(c=>c.id===v.id?v:c)});setModal(null)}}/>:<ConfirmDelete name={modal.item.name} onCancel={()=>setModal(null)} onConfirm={()=>remove(modal.item.id)}/>}</Modal>}</>}
function ClientCard({data:c,onView,onEdit,onDelete}){return <div className="client-card"><div className="client-top"><span className="initial">{c.initials}</span><div><b>{c.name}</b><small>{c.id}</small></div><Status status={c.status}/></div><p>✉ {c.email}</p><p>☎ {c.phone}</p><p>♟ {c.clinician}</p><div className="card-actions"><button className="primary small" onClick={onView}><Eye size={13}/> View Details</button><button className="outline small" onClick={onEdit}><Pencil size={13}/> Edit</button><button className="danger-btn small" aria-label="Delete" onClick={onDelete}><Trash2 size={13}/></button></div></div>}
function ClientDetail({c}){return <div className="detail-grid"><div className="detail-hero"><span className="large-initial">{c.initials}</span><div><h2>{c.name}</h2><p>{c.id}</p><Status status={c.status}/></div></div><Info label="Email" value={c.email}/><Info label="Phone" value={c.phone}/><Info label="Date of Birth" value={c.dob}/><Info label="Address" value={c.address}/><Info label="Assigned Clinician" value={c.clinician}/></div>}
function Status({status}){return <span className={'status '+status.toLowerCase()}><i/>{status}</span>}

function ClientProfile({nav,data,setData}){const c=data.clients[0]||seed.clients[0]; const [modal,setModal]=useState(null); return <><Header title="Client Profile" sub={`${c.name} · ${c.id}`}/><div className="profile-layout"><section className="profile-card"><div className="profile-banner"><span className="large-initial">{c.initials}</span><div><h2>{c.name}</h2><p>Client ID: {c.id}</p></div><div className="banner-actions"><button className="outline" onClick={()=>setModal('delete')}><Trash2 size={14}/> Delete</button><button className="primary" onClick={()=>setModal('edit')}><Pencil size={14}/> Edit</button></div></div><div className="profile-info"><Info label="Email" value={c.email}/><Info label="Phone" value={c.phone}/><Info label="Date of Birth" value={c.dob}/><Info label="Address" value={c.address}/></div></section><nav className="tabs"><button onClick={()=>nav('/medication')}>Medication</button><button onClick={()=>nav('/favorite-activities')}>Favorite Activities</button><button onClick={()=>nav('/daily-care')}>Daily Care</button><button onClick={()=>nav('/client-documents')}>Client Documents</button><button onClick={()=>nav('/reports')}>View Report</button></nav></div>{modal&&<Modal title={modal==='edit'?'Edit Client':'Delete Client'} onClose={()=>setModal(null)}>{modal==='edit'?<InlineEdit item={c} fields={['name','email','phone','clinician','status']} onSave={v=>{setData({...data,clients:data.clients.map(x=>x.id===v.id?v:x)});setModal(null)}}/>:<ConfirmDelete name={c.name} onCancel={()=>setModal(null)} onConfirm={()=>{setData({...data,clients:data.clients.filter(x=>x.id!==c.id)});setModal(null);nav('/clients')}}/>}</Modal>}</>}
function Info({label,value}){return <div className="info"><small>{label}</small><b>{value}</b></div>}
function ClientSub({title,nav,type}){const [modal,setModal]=useState(false);return <><Header title={title} sub="Client profile · John Doe"/><section className="section-card"><div className="section-title"><div><span className="eyebrow">CLIENT CARE</span><h2>{title}</h2></div><button className="primary" onClick={()=>setModal(true)}><Plus size={14}/> Add New</button></div>{type==='medication'?<Table cols={['Medication','Dosage','Frequency','Start Date','Status','Action']} rows={[['Paracetamol 500mg','500mg','As needed','10 Jan 2026','Active','View'],['Amlodipine','5mg','Once daily','10 Jan 2026','Active','View'],['Vitamin D','1000 IU','Once daily','10 Jan 2026','Active','View']]}/>:type==='activities'?<Cards labels={['Morning walks','Listening to music','Gardening','Reading']}/>:<Cards labels={['Personal hygiene','Meal preparation','Medication support','Mobility assistance']}/>}</section>{modal&&<Modal title={'Add '+title} onClose={()=>setModal(false)}><Form fields={type==='medication'?['Medication','Dosage','Frequency','Start Date']:['Activity Name','Notes']} submit={'Save '+title} onSubmit={()=>setModal(false)}/></Modal>}<BackLink nav={nav}/></>}
function BackLink({nav}){return <button className="back-link" onClick={()=>nav('/client-profile')}><ArrowLeft size={15}/> Back to Client Profile</button>}
function Documents({nav}){return <><Header title="Client Documents" sub="Documents uploaded for John Doe."/><section className="section-card"><div className="upload-row"><div><h2>Documents</h2><p>Keep care records current and accessible.</p></div><button className="primary" onClick={()=>window.alert('Client document upload form opened.')}><Upload size={15}/> Upload Document</button></div><Table cols={['Document','Type','Uploaded','Expiry','Status','Action']} rows={seed.documents.map(d=>[d.name,d.type,d.uploaded,d.expiry,d.status,'View'])}/></section><BackLink nav={nav}/></>}
function Reports({nav,data,setData}){const [modal,setModal]=useState(null); const remove=id=>{setData({...data,reports:data.reports.filter(r=>r.id!==id)});setModal(null)}; return <><Header title="View Report" sub="Previous submitted reports for John Doe."/><section className="section-card"><div className="section-title"><div><span className="eyebrow">REPORTS</span><h2>Submitted Reports</h2></div><button className="outline" onClick={()=>nav('/report-history')}>View Previous Report</button></div><Table cols={['Report Date','Submitted By','Type','Status','Action']} rows={data.reports.map(r=>[r.date,r.by,r.type,r.status,<div className="row-actions"><button className="table-link" onClick={()=>setModal({type:'view',item:r})}><Eye size={13}/> View</button><button className="table-link" onClick={()=>setModal({type:'edit',item:r})}><Pencil size={13}/> Edit</button><button className="table-danger" onClick={()=>setModal({type:'delete',item:r})}><Trash2 size={13}/></button></div>])}/></section>{modal&&<Modal title={modal.type==='delete'?'Delete Report':modal.type==='edit'?'Edit Report':'Report Details'} onClose={()=>setModal(null)}>{modal.type==='view'?<ReportDetail r={modal.item}/>:modal.type==='edit'?<InlineEdit item={modal.item} fields={['date','by','type','status']} onSave={v=>{setData({...data,reports:data.reports.map(r=>r.id===v.id?v:r)});setModal(null)}}/>:<ConfirmDelete name={`${modal.item.type} dated ${modal.item.date}`} onCancel={()=>setModal(null)} onConfirm={()=>remove(modal.item.id)}/>}</Modal>}</>}
function ReportDetail({r}){return <div className="report-paper"><div className="report-header"><FileText/><div><h2>{r.type}</h2><p>{r.date} · Submitted by {r.by}</p></div><Status status={r.status}/></div><hr/><h3>Care Summary</h3><p>Client received planned support throughout the day. Medication, meals, personal care and activities were recorded.</p><h3>Submission status</h3><p>This report was submitted successfully and is available in the portal history.</p></div>}
function ReportHistory({nav}){return <><Header title="Previous Submitted Report" sub="Report dated 18 August 2026."/><ReportDetail r={seed.reports[0]}/><BackLink nav={nav}/></>}

function EditClient({nav,data,setData}){const c=data.clients[0]; return <><Header title="Edit Client" sub="Update client information."/><Form fields={['First Name','Last Name','Email Address','Phone Number','Date of Birth','Address','Emergency Contact','Care Notes']} submit="Save Changes" onSubmit={()=>nav('/client-profile')}/><BackLink nav={nav}/></>}
function Expiry({nav}){return <><Header title="Expiry Document Alert" sub="Documents approaching or past their expiry date."/><section className="section-card"><Table cols={['Client','Document','Expiry Date','Days Left','Status','Action']} rows={[['John Doe','Identity Document','04 Jan 2026','Expired','Expired','View'],['Emily Smith','Care Plan','22 Aug 2026','4 days','Expiring Soon','View'],['Michael Brown','Medical Record','02 Sep 2026','15 days','Expiring Soon','View']]}/></section></>}
function Staff({nav,data,setData}){const [modal,setModal]=useState(null); const remove=id=>{setData({...data,staff:data.staff.filter(s=>s.id!==id)});setModal(null)}; return <><Header title="Manage Staff" sub="View and manage staff information."/><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search staff..."/></div><button className="primary" onClick={()=>nav('/add-staff')}><Plus size={15}/> Add Staff</button></div><div className="client-grid">{data.staff.map(s=><div className="client-card" key={s.id}><div className="client-top"><span className="initial">{s.initials}</span><div><b>{s.name}</b><small>{s.role} · {s.id}</small></div><Status status={s.status}/></div><p>✉ {s.email}</p><p>Role: {s.role}</p><div className="card-actions"><button className="primary small" onClick={()=>setModal({type:'view',item:s})}><Eye size={13}/> View</button><button className="outline small" onClick={()=>setModal({type:'edit',item:s})}><Pencil size={13}/> Edit</button><button className="danger-btn small" onClick={()=>setModal({type:'delete',item:s})}><Trash2 size={13}/></button></div></div>)}</div>{modal&&<Modal title={modal.type==='delete'?'Delete Staff':modal.type==='edit'?'Edit Staff':'Staff Profile'} onClose={()=>setModal(null)}>{modal.type==='view'?<StaffDetail s={modal.item}/>:modal.type==='edit'?<InlineEdit item={modal.item} fields={['name','role','email','status']} onSave={v=>{setData({...data,staff:data.staff.map(s=>s.id===v.id?v:s)});setModal(null)}}/>:<ConfirmDelete name={modal.item.name} onCancel={()=>setModal(null)} onConfirm={()=>remove(modal.item.id)}/>}</Modal>}</>}
function StaffDetail({s}){return <div className="detail-grid"><div className="detail-hero"><span className="large-initial">{s.initials}</span><div><h2>{s.name}</h2><p>{s.role} · {s.id}</p><Status status={s.status}/></div></div><Info label="Email" value={s.email}/><Info label="Phone" value={s.phone}/><Info label="Employment" value={s.employment}/><Info label="Start Date" value={s.startDate}/></div>}
function StaffProfile({nav,data,setData}){const s=data.staff[0]||seed.staff[0]; const [modal,setModal]=useState(null); return <><Header title="Staff Profile" sub={`${s.name} · ${s.role}`}/><section className="profile-card"><div className="profile-banner"><span className="large-initial">{s.initials}</span><div><h2>{s.name}</h2><p>{s.role} · Staff ID: {s.id}</p></div><div className="banner-actions"><button className="outline" onClick={()=>setModal('delete')}><Trash2 size={14}/> Delete</button><button className="primary" onClick={()=>setModal('edit')}><Pencil size={14}/> Edit</button></div></div><div className="profile-info"><Info label="Email" value={s.email}/><Info label="Phone" value={s.phone}/><Info label="Employment" value={s.employment}/><Info label="Start Date" value={s.startDate}/></div></section><nav className="tabs"><button onClick={()=>nav('/staff-documents')}>Uploaded Staff Document</button><button onClick={()=>nav('/staff-expiry')}>Expiry Staff Document</button><button onClick={()=>nav('/upload-staff-document')}>Upload Staff Document</button><button onClick={()=>nav('/induction')}>Staff Induction</button></nav>{modal&&<Modal title={modal==='edit'?'Edit Staff':'Delete Staff'} onClose={()=>setModal(null)}>{modal==='edit'?<InlineEdit item={s} fields={['name','role','email','status']} onSave={v=>{setData({...data,staff:data.staff.map(x=>x.id===v.id?v:x)});setModal(null)}}/>:<ConfirmDelete name={s.name} onCancel={()=>setModal(null)} onConfirm={()=>{setData({...data,staff:data.staff.filter(x=>x.id!==s.id)});setModal(null);nav('/staff')}}/>}</Modal>}</>}
function StaffDocuments({nav}){return <><Header title="Uploaded Staff Document" sub="Documents for John Smith."/><section className="section-card"><Table cols={['Document','Type','Uploaded','Expiry','Status','Action']} rows={[['Passport.pdf','Identity','04 Jan 2025','04 Jan 2030','Valid','View'],['Training Certificate.pdf','Training','14 May 2026','14 May 2028','Valid','View'],['DBS Check.pdf','Compliance','10 Jan 2024','10 Jan 2027','Valid','View']]}/></section><BackLink nav={nav}/></>}
function StaffExpiry({nav}){return <><Header title="Expiry Staff Document" sub="Staff documents requiring attention."/><section className="section-card"><Table cols={['Document','Expiry Date','Status','Action']} rows={[['First Aid Certificate','20 Aug 2026','Expiring Soon','View'],['Care Certificate','01 Sep 2026','Expiring Soon','View'],['DBS Check','10 Jan 2027','Valid','View']]}/></section><BackLink nav={nav}/></>}
function UploadStaff({nav}){return <><Header title="Upload Staff Document" sub="Upload a document for John Smith."/><Form fields={['Document Name','Document Type','Expiry Date','Description']} submit="Upload Document" upload onSubmit={()=>nav('/staff-documents')}/><BackLink nav={nav}/></>}
function EditStaff({nav,add,data,setData}){const [values,setValues]=useState(add?{}:data.staff[0]); const submit=e=>{e.preventDefault(); if(add){const initials=(values.name||'New Staff').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(); const item={...values,id:'ST-'+String(data.staff.length+1).padStart(3,'0'),initials,status:values.status||'Active',phone:values.phone||'+1 (555) 000-0000',employment:values.employment||'Full Time',startDate:values.startDate||'18 August 2026'};setData({...data,staff:[...data.staff,item]});nav('/staff')}else{setData({...data,staff:data.staff.map(s=>s.id===values.id?{...s,...values}:s)});nav('/staff-profile')}}; return <><Header title={add?'Add Staff':'Edit Staff'} sub={add?'Create a new staff profile.':'Update John Smith information.'}/><DynamicForm values={values} setValues={setValues} fields={['name','role','email','phone','status','employment','startDate','address']} labels={{name:'Full Name',role:'Role',email:'Email Address',phone:'Phone Number',status:'Status',employment:'Employment Type',startDate:'Start Date',address:'Address'}} submit={add?'Add Staff':'Save Changes'} onSubmit={submit}/><BackLink nav={nav}/></>}
function Policies({nav}){const [modal,setModal]=useState(null); const policies=['Medication Policy','Safeguarding Policy','Health and Safety Policy','Staff Code of Conduct']; return <><Header title="Policy" sub="Manage homecare policies and procedures."/><section className="section-card"><div className="section-title"><div><span className="eyebrow">COMPLIANCE</span><h2>Policies</h2></div><button className="primary" onClick={()=>nav('/upload-policy')}><Upload size={14}/> Upload Policy</button></div><div className="policy-list">{policies.map((x,i)=><div key={x}><FileText/><div><b>{x}</b><span>Updated 12 Aug 2026</span></div><button className="outline small" onClick={()=>setModal(x)}>View</button></div>)}</div></section>{modal&&<Modal title={modal} onClose={()=>setModal(null)}><div className="policy-detail"><FileText size={40}/><h2>{modal}</h2><p>This policy is available to authorised administrators. Review, download or update the policy document from the compliance workflow.</p><button className="primary" onClick={()=>window.alert('Policy download prepared.')}><Download size={15}/> Download Policy</button></div></Modal>}</>}
function UploadPolicy({nav}){return <><Header title="Upload Policy" sub="Add a new policy document."/><Form fields={['Policy Name','Policy Type','Effective Date','Review Date','Description']} submit="Upload Policy" upload onSubmit={()=>nav('/policies')}/><BackLink nav={nav}/></>}
function GenerateReport({nav}){return <><Header title="Generate Report" sub="Create a report from portal records."/><Form fields={['Report Type','Start Date','End Date','Client','Staff Member']} submit="Generate Report" onSubmit={()=>nav('/reports')}/><BackLink nav={nav}/></>}
function AuditLog(){return <><Header title="Audit Log" sub="Track administrator activity across the portal."/><section className="section-card"><Table cols={['Date & Time','User','Action','Module','IP Address']} rows={seed.audit}/></section></>}
function Induction({nav}){const [modal,setModal]=useState(null); const rows=[['John Smith','Care Worker','12 Jan 2024','Completed'],['Emma Wilson','Senior Carer','08 Mar 2025','In Progress'],['Sarah Williams','Care Worker','14 Jun 2026','In Progress']]; return <><Header title="Staff Induction" sub="Staff currently in the induction process."/><section className="section-card"><div className="section-title"><div><span className="eyebrow">PEOPLE & TRAINING</span><h2>Inducted Staff</h2></div><button className="primary" onClick={()=>nav('/add-induction')}><Plus size={14}/> Add New Staff Induction</button></div><Table cols={['Staff Name','Position','Start Date','Induction Status','Action']} rows={rows.map(r=>[...r,<div className="row-actions"><button className="table-link" onClick={()=>setModal({type:'view',name:r[0]})}><Eye size={13}/> View</button><button className="table-link" onClick={()=>setModal({type:'edit',name:r[0]})}><Pencil size={13}/> Edit</button><button className="table-danger" onClick={()=>setModal({type:'delete',name:r[0]})}><Trash2 size={13}/></button></div>])}/></section>{modal&&<Modal title={modal.type==='delete'?'Delete Induction':modal.type==='edit'?'Edit Induction':'Induction Details'} onClose={()=>setModal(null)}>{modal.type==='view'?<div className="detail-grid"><Info label="Staff Name" value={modal.name}/><Info label="Status" value="Completed"/><Info label="Training" value="Safeguarding, Medication, Health & Safety"/></div>:modal.type==='edit'?<DynamicForm values={{name:modal.name,status:'Completed'}} setValues={()=>{}} fields={['name','status','notes']} labels={{name:'Staff Name',status:'Induction Status',notes:'Notes'}} submit="Update Induction" onSubmit={e=>{e.preventDefault();setModal(null)}}/>:<ConfirmDelete name={modal.name+' induction record'} onCancel={()=>setModal(null)} onConfirm={()=>setModal(null)}/>}</Modal>}</>}
function InductionProfile({nav}){return <><Header title="Staff Induction Profile" sub="John Smith · Induction record"/><section className="profile-card"><div className="profile-banner"><span className="large-initial">JS</span><div><h2>John Smith</h2><p>Care Worker · Induction completed</p></div><button className="primary" onClick={()=>nav('/edit-induction')}><Pencil size={14}/> Edit</button></div><div className="induction-box">{['Orientation completed','Safeguarding training','Medication training','Health & Safety','Care plan training'].map(x=><label key={x}><input type="checkbox" defaultChecked/> {x}</label>)}</div></section><div className="profile-actions"><button className="primary" onClick={()=>nav('/add-induction')}><Plus size={14}/> Add New Staff Induction</button></div></>}
function EditInduction({nav,add}){return <><Header title={add?'Add New Staff Induction':'Edit Staff Induction'} sub="Staff induction record."/><Form fields={['Staff Name','Induction Date','Induction Type','Induction Status','Notes']} submit={add?'Save Induction':'Update Induction'} onSubmit={()=>nav('/induction')}/><BackLink nav={nav}/></>}
function Simple({title}){return <><Header title={title}/><section className="section-card"><p>Portal settings and preferences.</p></section></>}

function DynamicForm({values,setValues,fields,labels,submit,onSubmit}){const change=(k,v)=>setValues({...values,[k]:v}); return <section className="form-card"><form onSubmit={onSubmit}><div className="form-grid">{fields.map(f=><label key={f}>{labels[f]||f}<input value={values[f]||''} onChange={e=>change(f,e.target.value)} placeholder={'Enter '+(labels[f]||f).toLowerCase()}/></label>)}</div><div className="form-footer"><button type="button" className="outline" onClick={()=>window.history.back()}>Cancel</button><button className="primary" type="submit">{submit}</button></div></form></section>}
function Form({fielcd lads,submit,upload,onSubmit=()=>{},}){return <section className="form-card"><form onSubmit={e=>{e.preventDefault();onSubmit(e)}}><div className="form-grid">{fields.map(f=><label key={f} className={['Address','Description','Care Notes','Notes'].includes(f)?'wide':''}>{f}{upload&&f==='Document Name'?<input type="file"/>:<input placeholder={'Enter '+f.toLowerCase()}/>}</label>)}</div><div className="form-footer"><button type="button" className="outline" onClick={()=>window.history.back()}>Cancel</button><button className="primary" type="submit">{upload?<Upload size={15}/>:null}{submit}</button></div></form></section>}
function InlineEdit({item,fields,onSave}){const [v,setV]=useState({...item}); return <form className="inline-form" onSubmit={e=>{e.preventDefault();onSave(v)}}><div className="form-grid">{fields.map(f=><label key={f}>{f}<input value={v[f]||''} onChange={e=>setV({...v,[f]:e.target.value})}/></label>)}</div><button className="primary full" type="submit">Save Changes</button></form>}
function Modal({title,onClose,children}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><div><span className="eyebrow">DETAIL VIEW</span><h2>{title}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="modal-body">{children}</div></div></div>}
function ConfirmDelete({name,onCancel,onConfirm}){return <div className="confirm-delete"><div className="delete-icon"><Trash2/></div><h3>Delete this record?</h3><p>You are about to permanently delete <b>{name}</b>. This action cannot be undone.</p><div className="confirm-actions"><button className="outline" onClick={onCancel}>Cancel</button><button className="danger-solid" onClick={onConfirm}>Delete</button></div></div>}
function Table({cols,rows}){const [selected,setSelected]=useState(null);return <><div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const cells=Array.isArray(r)?r:[r];return <tr key={i}>{cells.map((x,j)=><td key={j}>{typeof x==='object'?x:(j===cells.length-1&&x==='View'?<button className="table-link" onClick={()=>setSelected({cells,cols})}><Eye size={13}/> View</button>:x)}</td>)}</tr>})}</tbody></table></div>{selected&&<Modal title="Record Details" onClose={()=>setSelected(null)}><div className="detail-grid">{selected.cells.slice(0,-1).map((value,i)=><Info key={i} label={selected.cols[i]||'Detail'} value={String(value)}/>)}</div></Modal>}</>}
function Cards({labels}){return <div className="mini-cards">{labels.map(x=><div key={x}><span><Check/></span><b>{x}</b><p>Recorded in client care plan.</p></div>)}</div>}

createRoot(document.getElementById('root')).render(<App/>);
